/**
 * Extracts the design-token rules from @astryxdesign/core/dist/astryx.css
 * and copies the other Astryx CSS files into assets/css/vendor/.
 *
 * astryx.css is ~100 KB of pre-compiled StyleX output; only the rules whose
 * selector list contains `:root` hold the 184 design tokens. Everything else
 * (hashed .x* component classes, @property registrations) is dead weight
 * without React, so we keep just the tokens, normalized to a bare `:root`
 * selector and re-wrapped in the original `astryx-base` layer so that the
 * `astryx-theme` layer from theme-neutral still wins where it overrides.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const vendorDir = join(root, 'assets', 'css', 'vendor');
mkdirSync(vendorDir, { recursive: true });

const astryxCss = readFileSync(
  require.resolve('@astryxdesign/core/astryx.css'),
  'utf8'
);

// Token rules look like `:root, .xHASH{--token:value;...}` and contain only
// declarations (no nested braces), so a flat regex is safe here.
const tokenRules = [];
const ruleRe = /(^|[}\s])(:root[^{}]*)\{([^{}]*)\}/g;
for (const match of astryxCss.matchAll(ruleRe)) {
  tokenRules.push(`:root {${match[3]}}`);
}

if (tokenRules.length === 0) {
  console.error('extract-tokens: no :root rules found in astryx.css — did the package layout change?');
  process.exit(1);
}

const banner = [
  '/* Astryx design tokens — generated by scripts/extract-tokens.mjs. Do not edit. */',
  `/* Source: @astryxdesign/core/dist/astryx.css (${tokenRules.length} token rules) */`
].join('\n');

writeFileSync(
  join(vendorDir, 'astryx-tokens.css'),
  `${banner}\n@layer astryx-base {\n${tokenRules.join('\n')}\n}\n`
);

copyFileSync(
  require.resolve('@astryxdesign/core/reset.css'),
  join(vendorDir, 'astryx-reset.css')
);
copyFileSync(
  require.resolve('@astryxdesign/theme-neutral/theme.css'),
  join(vendorDir, 'astryx-theme-neutral.css')
);

const varCount = (readFileSync(join(vendorDir, 'astryx-tokens.css'), 'utf8').match(/--[\w-]+\s*:/g) || []).length;
console.log(`extract-tokens: wrote astryx-tokens.css (${tokenRules.length} rules, ${varCount} custom properties), copied reset + theme-neutral.`);
